"""Detailed positions (GK LB CB RB LM CM RM ST) for players Transfermarkt can't give us, plus overrides for
famous utility players. Primary position first. Hand-compiled - corrections welcome."""

MANUAL = """
Emile Heskey: ST/LM
John O'Shea: CB/RB/CM
Kevin Davies: ST
Alan Shearer: ST
Andrew Cole: ST
Lee Bowyer: CM/RM
Ray Parlour: RM/CM
Robbie Fowler: ST
Luke Young: RB/CB
Stephen Carr: RB
Chris Perry: CB
Les Ferdinand: ST
Steve Watson: RB/CB/RM
Nick Barmby: CM/RM/LM
Kenny Cunningham: CB/RB
Son Heung-Min: LM/ST/RM
Jason Dodd: RB
Gary McAllister: CM
Kevin Kilbane: LM/LB
Luis Antonio Valencia: RB/RM
Martin Keown: CB
Paul Telfer: RB/RM
Ben Davies: LB/CB
Dennis Bergkamp: ST/CM
Lee Dixon: RB
Shola Ameobi: ST
Mark Hughes: ST
Graham Stuart: CM/ST
Titus Bramble: CB
Claus Lundekvam: CB
Matt Upson: CB
Zat Knight: CB
Lee Carsley: CM
Charles N'Zogbia: LM/RM
Andy O'Brien: CB
Robert Lee: CM/RM
Dominic Matteo: CB/LB
Steve McManaman: RM/LM
Lee Cattermole: CM
Matthew Le Tissier: CM/ST
Duncan Ferguson: ST
Joey Barton: CM/RM
David Batty: CM
Des Walker: CB
Fernandinho: CM/CB
Jason Euell: ST/CM
Carlton Palmer: CM/CB
Gary Pallister: CB
Tony Adams: CB
Richard Shaw: CB/RB
Yakubu: ST
Matt Oakley: CM
Ricardo Gardner: LM/LB
Niall Quinn: ST
Robbie Earle: CM
Francis Benali: LB/CB
Fredrik Ljungberg: RM/LM
Mark Viduka: ST
Brede Hangeland: CB
Ian Harte: LB
Simon Charlton: LB
Michael Gray: LB/LM
Ole Gunnar Solskjaer: ST/RM
Tugay: CM
Bruno Fernandes: CM
Phil Babb: CB
Mark Pembridge: LM/CM
Dean Holdsworth: ST
N'Golo Kanté: CM
Scot Gemmill: CM
Don Hutchison: CM/ST
Tony Cottee: ST
Andy Hinchcliffe: LB
Colin Hendry: CB
Danny Mills: RB
Chris Armstrong: ST
Andy Townsend: CM
Dan Petrescu: RB/RM
Marcus Bent: ST
Gary O'Neil: CM/RM
Jim Magilton: CM
Ian Wright: ST
Ben Thatcher: LB
Kevin Richardson: CM
Paul Robinson: LB
Matthew Jarvis: LM/RM
Paul Williams: CB
Matt Holland: CM
Darren Huckerby: ST/LM
John Barnes: CM/LM
Kenneth Monkou: CB
Kevin Gallacher: ST
Ahmed Elmohamady: RB/RM
Lucas Radebe: CB
Dean Saunders: ST
Rodri: CM/CB
Steve Bould: CB
Earl Barrett: RB/CB
Neil Ruddock: CB
Steven Taylor: CB
Tomasz Radzinski: ST
Steve Howey: CB
Alexandre Song: CM/CB
Clive Wilson: LB
Colin Calderwood: CB
Andrew Johnson: ST
Ki Sung-Yueng: CM
Ian Nolan: RB/LB
Oyvind Leonhardsen: CM/RM
Lee Clark: CM
Peter Beardsley: ST/CM
Gunnar Halle: RB
Vinnie Jones: CM
Mark Draper: CM
Alan Kimble: LB
Alf Inge Haaland: CB/CM/RB
Boudewijn Zenden: LM
Andy Sinton: LM/RM
Marcos Alonso: LB
Benito Carbone: ST/CM
Ian Rush: ST
Iain Dowie: ST
Lee Sharpe: LM/LB
Justin Edinburgh: LB
Tony Dorigo: LB
Benjamin White: RB/CB
Andrew Todd: CB/CM
Ivan Campo: CM/CB
John Scales: CB
Michael Ball: LB/CB
Neal Ardley: RM
Spencer Prior: CB
Chris Riggott: CB
Steve Clarke: RB
Abdoulaye Diagne-Faye: CM/CB
Paul McGrath: CB
Eddie Newton: CM
Stan Collymore: ST
Brian McClair: CM/ST
Stig Inge Bjornebye: LB
David Junior Hoilett: LM/RM
Mathias Jensen: CM
Michael Duberry: CB
Graham Hyde: CM
Ian Marshall: ST/CB
Ramires: CM/RM
Steffen Iversen: ST
Michael Turner: CB
Claus Jensen: CM
Craig Burley: CM
Dean Blackwell: CB
Reece James: RB
Eric Cantona: ST
Jason McAteer: RM/CM/RB
Paulo Wanchope: ST
Jon Newsome: CB
Lars Bohinen: CM
Rob Jones: RB
John Beresford: LB
Jonás Gutiérrez: LM/RM
Mame Biram Diouf: ST/RM
Park Ji-Sung: RM/LM/CM
Peter Ndlovu: ST/LM
Bobby Decordova-Reid: RM/ST
David Howells: CM
Andrei Kanchelskis: RM
Antoine Sibierski: CM/ST
Fabinho: CM/CB
Alessandro Pistone: LB/CB
Florent Malouda: LM
Brian McBride: ST
Bruno N'Gotty: CB
Nikolaos Dabizas: CB
Steve Bruce: CB
Alain Goma: CB
Brian Borrows: RB
Geremi: RM/RB/CM
Jacob Laursen: CB
Lomana Lua Lua: ST/LM
Daryl Janmaat: RB
Garry Parker: CM
Ian Bishop: CM
Matt Jackson: RB/CB
Vitalii Mykolenko: LB
Henrik Pedersen: ST
Mark Bright: ST
Neil Cox: RB
Terry Phelan: LB
Mark Bowen: LB
Tim Breacker: RB
Liam Rosenior: RB
Ricardo Fuller: ST
Emmanuel Petit: CM
Fred: CM
Stelios Giannakopoulos: RM
Cheick Tioté: CM
Gary Mabbutt: CB
Guy Whittingham: ST
Ashley Ward: ST
Mark Wright: CB
Chris Marsden: CM/LB
Gary Rowett: CB/RB
Rufus Brevett: LB
David Hirst: ST
Gudni Bergsson: CB
Malcolm Christie: ST
Julian Dicks: LB/CB
Per Frandsen: CM
Hwang Hee-Chan: ST/LM
Niclas Alexandersson: RM
Simon Barker: CM
David Bardsley: RB
Keith Curle: CB
Robbie Elliott: LB
Barry Horne: CM
Roland Nilsson: RB
Charlie Daniels: LB
Marian Pahars: ST
Bryan Hughes: CM
Sylvain Legwinski: CM
Anders Svensson: CM/RM
Marc Edworthy: RB
Nicky Hunt: RB
Tuncay Sanli: ST/LM
David Phillips: CM/RM
Jason Dozzell: CM
João Pedro: ST
Moritz Volz: RB
David Hopkin: CM
Dean Austin: RB
Mark Fish: CB
Andy Clarke: ST
Cristian Romero: CB
Jonathan Fortune: CB
Shaun Bartlett: ST
Sun Jihai: RB/LB
Egil Ostenstad: ST
Johan Elmander: ST
John Ebbrell: CM
Seth Johnson: CM
Andy Booth: ST
Chris Fairclough: CB
Francis Jeffers: ST
Ronnie Rosenthal: ST
Andy Linighan: CB
Mike Newell: ST
Alan McDonald: CB
Steffen Freund: CM
Steve Nicol: RB/CB
Chris Waddle: RM
Olivier Bernard: LB
Wilfried Bony: ST
Erland Johnsen: CB
Gilles Grimandi: CB/CM/RB
José Holebas: LB
Nigel Worthington: LB
Kevin Lisbie: ST
Mitoma Kaoru: LM
David Linighan: CB
John Sheridan: CM
José Bosingwa: RB
Paul Rideout: ST
Carl Cort: ST
Gary Ablett: CB/LB
Jo Tessem: CM/RM
Nigel Clough: CM/ST
Paquetá: CM
Geraint Williams: CM
Joey O'Brien: RB/CM
Rafael: RB
Aliaksandr Hleb: CM/RM
Darren Williams: RB/CB
Gavin Peacock: CM
Gordon Watson: ST
Carl Tiler: CB
Francisco Femenía: RB
Ian Holloway: CM
Jonathan Otto: RB
Michael Thomas: CM
Mike Milligan: CM
Ian Crook: CM
Richard Hall: CB
Sylvain Wiltord: ST/RM
Toti Gomes: CB/LB
Anderson: CM
Ray Houghton: RM/CM
Rodrigo Moreno: ST
Shaun Teale: CB
Chris Kiwomya: ST
Daniel Drinkwater: CM
Jesper Grønkjaer: RM
Jonny Howson: CM
Mike Whitlow: LB
Andy Myers: LB/CB
Marcus Hall: LB
Georgi Kinkladze: CM
Mathias Jorgensen: CB
Chris Coleman: CB
George Boyd: LM/CM
John Wark: CB/CM
Stefan Schwarz: CM
André Gomes: CM
Andy Melville: CB
Andy Pearce: CB
David White: RM/ST
John Robinson: RM
Marc Overmars: LM
Anders Limpar: LM
Brett Ormerod: ST
Craig Fleming: CB
David N'Gog: ST
Jimmy Phillips: LB
Richard Jobson: CB
Richard Rufus: CB
Carl Bradshaw: RB/CM
John Jensen: CM
Lee Chapman: ST
Scott Sellars: LM
Çaglar Söyüncü: CB
Allan Nielsen: CM
Dara O'Shea: CB
Christophe Berra: CB
Denilson: CM
Gordon Strachan: RM/CM
Heidar Helguson: ST
John Polston: CB
Mick Stockwell: RM/CM
Phil Whelan: CB
Philippe Albert: CB
Yehor Yarmoliuk: CM
Stefano Eranio: RM/CM
John Collins: CM
John Pantsil: RB
Mike Marsh: CM
Allan-Roméo Nyom: RB
Graham Fenton: ST
Jamie O'Hara: CM
Christian Ziege: LB/LM
Darren Ambrose: CM/RM
Nathan Blake: ST
Neil Adams: RM
Sean Flynn: RM/CM
Steve Harkness: LB/RB
Anthony Barness: RB/LB
Jimmy Bullard: CM
Joe Parkinson: CM
Marc Rieper: CB
Savo Milosevic: ST
Steve Sedgley: CB/CM
Barry Venison: CB/CM/RB
Javier Garrido: LB
Mick Harford: ST
Yoan Gouffran: LM/ST
David Platt: CM
Horacio Carbonari: CB
Gareth Hall: RB
Michael Bridges: ST
Paul Parker: RB/CB
Steve Walsh: CB/ST
Trond Egil Soltvedt: CM
Mark Davies: CM
Paul Beesley: CB/LB
Paul Bracewell: CM
Bryan Roy: ST/LM
Hatem Ben Arfa: RM/CM
Jan Åge Fjørtoft: ST
Jeremy Goss: CM
Mark Atkins: CM
Neil Redfearn: CM
Ray Wilkins: CM
Robbie Slater: RM
Ian Culverhouse: RB
Alexei Smertin: CM
David Rennie: CB/CM
Gary Elkins: LM/LB
Keith Rowland: LB/LM
Michel Vonk: CB
Paul Allen: RM/CM
Rob Newman: CB/CM
Steve Yates: CB
Andy Roberts: CM/CB
Marcus Stewart: ST
Oleg Luzhny: RB
Christian Atsu: LM/RM
Eddie McGoldrick: RM
Fabio: RB/LB
John Pemberton: CB/RB
John Williams: ST
David Lee: CB/CM
Doriva: CM
Edu: CM/LM
Jamie Pollock: CM
Richard Holden: LM
Ron Vlaar: CB
Illia Zabarnyi: CB
John Fashanu: ST
Stephen Hughes: CM/LM
Stephen Jordan: LB
Temuri Ketsbaia: CM/ST
Luis García: RM/ST/CM
Marcos Rojo: CB/LB
Neil Thompson: LB
Slaven Bilic: CB
Abel Xavier: RB/CB
Alan Neilson: RB
Alan Smith: ST
Barry Hayles: ST
David Rocastle: RM/CM
Nigel Pearson: CB
Roy Wegerle: ST
Stephen Froggatt: LM/LB
Alan Kernaghan: CB
Mark Walters: LM
Robert Ullathorne: LB
Dalian Atkinson: ST
Gavin Johnson: LM/LB
Marc Vivien Foe: CM
Robert Molenaar: CB
Brian McAllister: CB
Clint Hill: CB/LB
Jamie Lawrence: RM
Peter Fear: CM
Alun Armstrong: ST
Andy Thorn: CB
Eddie Youds: CB
Laurent Charvet: RB
Stuart McCall: CM
Craig Fagan: ST/RM
Lee Young-Pyo: LB
Mikkel Beck: ST
Scott Fitzgerald: CB
Steve McMahon: CM
Tyrone Mears: RB
Fábio Rochemback: CM
Joselu: ST
Mal Donaghy: CB
Steve Morgan: LB
Thiago: CM
Wim Jonk: CM
Glyn Hodges: LM/CM
Marc Pugh: LM
Matt Holmes: LM
Neil Heaney: LM
Nigel Spackman: CM
Danny Williamson: CM
Kostas Tsimikas: LB
Paul Gascoigne: CM
Raul Meireles: CM
Sascha Riether: RB
Ally Pickering: RB
John Hendrie: ST/RM
Paul Bernard: CM
Sasa Curcic: CM/LM
Youssef Chippo: CM
Bafétimbi Gomis: ST
Fabrizio Ravanelli: ST
Fernando: CM
Francesco Baiano: ST
Mick Quinn: ST
Pontus Kaamark: CB/RB
Ramon Vega: CB
Steve Redmond: CB
Gary Penrice: ST
Ibrahima Diallo: CM
Jason Lee: ST
Willie Boland: CM
Antony: RM
Diafra Sakho: ST
Elano: CM/RM
Gaizka Mendieta: RM/CM
Jay Bothroyd: ST
Stuart Barlow: ST
Bontcho Guenchev: ST/LM
David Hillier: CM
Gareth Farrelly: CM
Tahar El-Khalej: CB
Andy Dawson: LB
Fitzroy Simpson: CM
Jon Goodman: ST
Karl Ready: CB
Karl-Heinz Riedle: ST
Michael Chopra: ST
Michael Svensson: CB
Stefan Schnoor: CB/LB
Steve Morrow: CB/CM
Aliou Cisse: CM
Bradley Allen: ST
Diniyar Bilyaletdinov: LM/CM
Fernando Nelson: RB
Ibrahim Sangaré: CM
Neil Pointon: LB
Serhiy Rebrov: ST
André-Frank Anguissa: CM
Emre: CM
Gianluca Vialli: ST
Keith Fahey: CM
Martin Allen: CM
Özalan Alpay: CB
Alan Reeves: CB
Claus Thomsen: CM/CB
Endo Wataru: CM
Jake O'Brien: CB/RB
Micky Adams: LB
Robert Koren: CM
Carl Leaburn: ST
Eoin Jess: CM/ST
Jürgen Klinsmann: ST
Laurent Depoitre: ST
Marc Hottiger: RB
Paul Stewart: ST/CM
Simon Rodger: LM/CM
Trevor Morley: ST
Trézéguet: RM/LM
Albert Riera: LM
Daryl Sutch: RB/CM
Graeme Sharp: ST
John McGreal: CB
Julian Darby: CM/CB
Kevin Moran: CB
Steve Marlet: ST
Stuart Slater: RM
Andy Hill: RB/CB
David Sommeil: CB
Frank Yallop: RB
Graham Kavanagh: CM
Juliano Belletti: RB
Mark Venus: LB/CB
Martin Djetou: CB/CM
Nick Henry: CM
Stuart Nethercott: CB
Vegard Heggem: RB
Bojan: ST/RM
David Hughes: CM
Erik Nevland: ST
Javi García: CM
John Humphrey: RB
Mykhailo Mudryk: LM
Nicky Marker: CB/CM
Paul Bosvelt: CM
Paul Walsh: ST
Sávio: RM/LM
Allan: CM
Bjarne Goldbæk: RM
Chris Morris: RB
Dane Whitehouse: LM
Hameur Bouazza: LM/ST
Ian Snodin: CM
Jakob Kjeldbjerg: CB
Joe-Max Moore: ST
Paul Rogers: CM
Simon Milton: RM
Albert Sambi: CM
Danny Tiatto: LB/LM
Eric Young: CB
Ian Butterworth: CB
Peter Ramage: RB/CB
Willie Falconer: ST/CM
Danilo: CM
David Busst: CB
Lawrie Sanchez: CM
Mark Stein: ST
Martijn Reuser: LM/CM
Theo Zagorakis: CM

# famous utility men / players whose Transfermarkt position is only their late-career role
Dion Dublin: ST/CB
Gareth Bale: RM/LM/LB/ST
James Milner: CM/RM/LB/RB
Chris Sutton: ST/CB
Phil Neville: RB/LB/CM
Ashley Young: LM/RM/LB/RB
Michail Antonio: ST/RM/RB
Trent Alexander-Arnold: RB/CM
Oleksandr Zinchenko: LB/CM
Victor Moses: RM/RB
Kyle Walker: RB/CB
John Stones: CB/CM
Rio Ferdinand: CB
Mohamed Salah: RM/ST
Raheem Sterling: LM/RM/ST
Sadio Mané: LM/ST
Riyad Mahrez: RM
Ryan Giggs: LM/CM
Wayne Rooney: ST/CM
Paul Scholes: CM/ST
Frank Lampard: CM
Steven Gerrard: CM/RM/ST
Thierry Henry: ST/LM
Cristiano Ronaldo: RM/LM/ST
David Beckham: RM/CM
Gary Neville: RB
Jamie Carragher: CB/RB/LB
Javier Mascherano: CM/CB
Eric Dier: CB/CM
Declan Rice: CM/CB
Emre Can: CM/CB
David Luiz: CB/CM
Kieran Trippier: RB/LB
Tim Cahill: CM/ST
Marouane Fellaini: CM/ST
Kevin Nolan: CM/ST
Joshua King: ST/LM
Jordan Henderson: CM/RB
Robert Pirès: LM/CM
Freddie Ljungberg: RM/LM
Dennis Wise: CM/RM
Teddy Sheringham: ST/CM
Kevin De Bruyne: CM/RM
Bernardo Silva: RM/CM
Phil Foden: LM/CM/ST
Bukayo Saka: RM/LB
Leandro Trossard: LM/ST
Richarlison: ST/LM
Roberto Firmino: ST/CM
Heung-Min Son: LM/ST
Harry Kane: ST
Ashley Cole: LB
Patrice Evra: LB
Antonio Valencia: RB/RM
Gary Speed: CM/LM
Matt Le Tissier: CM/ST
Lee Sharpe: LM/LB
Danny Rose: LB/LM
Luke Shaw: LB/CB
Joshua Kimmich: CM/RB
Joël Matip: CB
Nathaniel Clyne: RB
Andrew Robertson: LB
Aaron Wan-Bissaka: RB
Ben Chilwell: LB
Kieran Gibbs: LB
Gaël Clichy: LB
Nacho Monreal: LB/CB
Cesar Azpilicueta: RB/CB/LB
César Azpilicueta: RB/CB/LB
Branislav Ivanovic: RB/CB
Pablo Zabaleta: RB
Bacary Sagna: RB
Glen Johnson: RB/LB
Leighton Baines: LB
Séamus Coleman: RB
Ricardo Pereira: RB/LM
Wes Brown: CB/RB
John Terry: CB
Vincent Kompany: CB
Nemanja Vidic: CB
Philippe Coutinho: CM/LM
Jóhann Gudmundsson: RM/LM
Nicolas Pépé: RM/ST
Joe Cole: LM/CM/RM
Theo Walcott: RM/ST
Jack Grealish: LM/CM
""".strip()

POSITIONS = {}
for line in MANUAL.splitlines():
    line = line.strip()
    if not line or line.startswith('#'):
        continue
    name, pos = line.rsplit(':', 1)
    POSITIONS[name.strip()] = pos.strip().split('/')
